services:
  diversedownloader:
    container_name: diversedownloader
    build: .
    ports:
      - "5353:8000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks: {}
